<div class="divinp">
    <h3>Solicitud fue procesada con Exito!</h3>
</div>
<div class="row">
    <div class="col-md-9">
        <h4 style="position:relative; left:35px"><b>Nombre:</b> <?php echo $nombtramite?> </h4>
        <h4 style="position:relative; left:35px"><b>Apellido:</b> <?php echo $apetramite?> </h4>
        <h4 style="position:relative; left:35px"><b>DNI:</b> <?php echo $dnitramite?> </h4>
        <h4 style="position:relative; left:35px"><b>Tipo de tramite:</b> <?php echo $tramite?> </h4>
    </div>
</div>

<div>
    <h4 style="position:relative; left:15px; margin-right: 10px">Después de dos días habiles de haber realizado la solicitud, usted podrá realizar consultas telefónicas al 
        <b>tel:(0388)-4233211</b> para informarse sobre el estado de su solicitud</h4>
</div>

<div class="divinp">
    <a href="/turnos/matriculado/index">
        <?php echo Html::img('turnos/BtnFinalizar.png', 'Finalizar', 'class="btnefe btnReduc"');?>
    </a>
</div>