<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//localhost/piwik/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 2]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>

<?php include_once("analyticstracking.php") ?>
<div>
    <?php //echo Html::img('turnos/MatYRen.gif','Matriculacion y Renovacion','class="img-responsive img1"')?>
</div>

<div class="row">
<div class="col-md-8">   
<div>
    <?php echo Html::img('turnos/AtencionAlPublico.gif','Atencion al pub','class="img-responsive img1"')?>
</div>
<div class='informacion'>
    <h4>
        <p>Registro y Matriculación de Profesionales de la Salud</p>
        <p>Martes, Miércoles y Jueves de 8 a 12 hs.</p>
        <p>Pasaje Ernesto Claros 75 - Dpto. 16</p>
        <p>Teléfono: (0388) - 4233211</p>
        <p>E-mail: matriculacionsalud@gmail.com </p>
        <p>CP (4600) - San Salvador de Jujuy - Jujuy - Argentina</p>
        
    </h4>
    
</div>
</div>
</div>

<hr id='sep'>

<div>
    <?php echo Html::img('turnos/ProfecionesComp.gif','Profeciones Comprendidas','class="img-responsive img1"')?>
</div>
<div class="paneles">
<div class="panel-group" id="accordion">
<!--  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title " data-toggle="collapse" data-parent="#accordion" href="#collapsea">
        AUXILIARATOS
      </h4>
    </div>
    <div id="collapsea" class="panel-collapse collapse">
        <div class="panel-body">
            -Agente Sanitario.
        </div>
    </div>
  </div>-->
  
 <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title " data-toggle="collapse" data-parent="#accordion" href="#collapseb">
        TECNICATURAS
      </h4>
    </div>
    <div id="collapseb" class="panel-collapse collapse">
        <div class="panel-body">
            -Acompañante Terapéutico<br>
            -Educador Sanitario<br>
            -Enfermero<br>
            -Instrumentador Quirúrgico<br>
            -Téc. en Citología<br>
            -Téc. en Emergencia Médica<br>
            -Téc. en Estadística<br>
            -Téc. en Esterilización<br>
            -Téc. en Farmacia<br>
            -Téc. en Hemoterapia<br>
            -Téc. en Hemoterapia<br>
            -Téc. en Laboratorio<br>
            -Téc. en Neurofisiología<br>
            -Téc. en Obstetricia<br>
            -Téc. en Prótesis y Órtesis<br>
            -Téc. Radiólogo<br>
            -Terapista Ocupacional
        </div>
    </div>
  </div>  
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title " data-toggle="collapse" data-parent="#accordion" href="#collapsec">
        GRADO UNIVERSITARIO
      </h4>
    </div>
    <div id="collapsec" class="panel-collapse collapse">
        <div class="panel-body">
            -Genetista<br>
            -Lic. en Educación para la Salud<br>
            -Lic. en Enfermería<br>
            -Lic. en Estadística en Salud<br>
            -Lic. en Obstetricia<br>
            -Lic. en Producción de Bioimagenes<br>
            -Lic. en Prótesis y Órtesis
        </div>
    </div>
  </div>  
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title " data-toggle="collapse" data-parent="#accordion" href="#collapseD">
        PROFESIONES COMPLEMENTARIAS
      </h4>
    </div>
    <div id="collapseD" class="panel-collapse collapse">
        <div class="panel-body">
            -Técnico en Estadística<br>
            -Psicomotricista <br>
            -Psicopedagogo <br>
            -Musicoterapeuta<br>
            -Tecnología Alimentaria <br>
            -Técnico en Alimentos <br>
            -Profesor en Educacación Especial<br>
            -Profesor en Educación Física
        </div>
    </div>
  </div> 

    
 </div> 
</div>


<hr id='sep'>

<div>
    <?php echo Html::img('turnos/Requisitos.gif','Requisitos','class="img-responsive img1"')?>
</div>
<div class="paneles">
<div class="panel-group" id="accordion1">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title " data-toggle="collapse" data-parent="#accordion1" href="#collapse1">
        MATRICULACIÓN DE PROFESIONALES UNIVERSITARIOS Y TÉCNICOS
      </h4>
    </div>
    <div id="collapse1" class="panel-collapse collapse">
        <div class="panel-body">
            * Fotocopia anverso y reverso del Documento Nacional de Identidad y acreditación de identidad presentando el 
          original del mencionado documento. <br>
          Los extranjeros deberán poseer documento nacional de identidad emitido por Autoridad Argentina y cumplir con 
          las condiciones migratorias previstas en la Ley 25.871 y legislación concordante. Carta de ciudadanía para el 
          caso de argentinos naturalizados.<br>
          * Original del Título/Diploma Universitario, que deberá cumplir con las condiciones de legalización pertinentes.<br>
          * Fotocopia doble faz en tamaño A4 del Título/Diploma debidamente legalizado, por la universidad o Institución 
          formadora y/o Escribano Público.<br>
          * Fotocopia en tamaño A4 del Analítico debidamente legalizado, por la universidad o Institución formadora y/o 
          Escribano Público <br>
          * Constancia de número de CUIT o CUIL.<br>
          * Certificado de Residencia, expedido por autoridad policial (vigencia 1 año).<br>
          * Declaración Jurada de datos personales del número de teléfono de línea y/o celular y dirección de correo 
          electrónico si tuviere.<br>
          * Carnet Sanitario vigente.<a href="http://salud.jujuy.gob.ar/" target="blank">(Web del Ministerio de Salud)</a><br>
          * Planilla Prontuarial actualizada.<br>
          * Certificado de Reincidencia vigente.<a href="http://www.dnrec.jus.gov.ar/Lugar_Tramite.aspx?c_prov=7&c_pais=12&m_priv=1&m_ofi=0&m_todos=0" target="_blank" >(Web del Registro Nacional de Reincidencia)</a> <br>
          * Pago de arancel correspondiente especificado en sección Aranceles.<br>
          * Carpeta colgante. <br>
          * En caso de poseer matricula de otra jurisdicción deberá presentar el certificado de ética o libre sanción 
          profesional correspondiente al último registro que conste en el título/diploma o certificado la misma tiene 30 
          días de validez de la fecha de emisión.<br>
          * Si la matricula fue dada de baja, presentar constancia de la misma.<br>
          
        </div>
    </div>
  </div>
    
    
<!--  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title" data-toggle="collapse" data-parent="#accordion" href="#collapse2">
        RE-MATRICULACIÓN DE PROFESIONALES UNIVERSITARIOS Y TÉCNICOS
      </h4>
    </div>
    <div id="collapse2" class="panel-collapse collapse">
      <div class="panel-body">
          
          * Presentación de la "Planilla de Turno Otorgado".<br>
          * Fotocopia anverso y reverso del Documento Nacional de Identidad y acreditación identidad presentando el 
          original del mencionado documento. <br>
          Los extranjeros deberán poseer documento nacional de identidad emitido por Autoridad Argentina y cumplir con 
          las condiciones migratorias previstas en la Ley 25.871 y legislación concordante. Carta de ciudadanía para el 
          caso de argentinos naturalizados.<br>
          * Original del Título/Diploma Universitario, que deberá cumplir con las condiciones de legalización especificadas
          ut supra.<br>
          * Fotocopia doble faz en tamaño A4 del Título/Diploma debidamente legalizado, por la universidad o Institución 
          formadora y/o Escribano Público.<br>
          * Constancia de número de CUIT o CUIL.<br>
          * Fotocopia en tamaño A4 del Analítico debidamente legalizado, por la universidad o Institución formadora y/o 
            Escribano Público. <br>
          * Certificado de Residencia, expedido por autoridad policial (vigencia 1 año).<br>
          * Declaración Jurada de datos personales del número de teléfono de línea y/o celular y dirección de correo 
          electrónico si tuviere.<br>
          * Carnet Sanitario vigente.<br>
          * Planilla Prontuarial actualizada.<br>
          * Certificado de Reincidencia vigente.<br>
          * En caso de poseer matricula de otra jurisdicción deberá presentar el certificado de ética o libre sanción profesional 
            correspondiente al último registro que conste en el título/diploma o certificado la misma tiene 30 días de validez de 
            la fecha de emisión. Si la matricula fue dada de baja constancia de la misma. <br>
          * Fotocopia de la credencial oportunamente otorgada para su agregación al legajo personal, o en su defecto la 
          respectiva denuncia de extravío.<br>
          * Certificado de ética o libre sanción profesional correspondiente al último registro que conste en el 
          título/diploma o certificado la misma tiene 30 días de validez de la fecha de emisión. Si la matricula fue 
          dada de baja constancia de la misma. <br>
          * Pago de arancel correspondiente especificado en ANEXO II.<br>
          * Carpeta colgante.<br>
    </div>
  </div>
  </div>   -->
      
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title" data-toggle="collapse" data-parent="#accordion1" href="#collapse3">
        REGISTRACIÓN DE PROFESIONES COMPLEMENTARIAS DE LA SALUD
      </h4>
    </div>
    <div id="collapse3" class="panel-collapse collapse">
        <div class="panel-body">
            * Presentación de la "Planilla de Turno Otorgado".<br>
            * Presentación de Formulario F-01 que deberá ser firmado como Declaración Jurada por el solicitante delante del agente 
            de registro del Ministerio de Salud <br>
            * Fotocopia anverso y reverso del Documento Nacional de Identidad y acreditación identidad presentando el original del 
            mencionado documento. <br>
            Los extranjeros deberán poseer documento nacional de identidad emitido por Autoridad Argentina y cumplir 
            con las condiciones migratorias previstas en la Ley 25.871 y legislación concordante. Carta de ciudadanía 
            para el caso de argentinos naturalizados.<br>
            * Original del Certificado, que deberá cumplir con las condiciones de registración y legalización.<br>
            * Fotocopia doble faz en tamaño A4 del Certificado debidamente legalizado por la Institución formadora y/o Escribano Público.<br>
            * Fotocopia en tamaño A4 del Analítico, que deberá cumplir con las condiciones de registración y legalización 
            pertinentes. <br>
            * Constancia de número de CUIT o CUIL.<br>
            * Certificado de Residencia, expedido por autoridad policial (Vigencia 1 año).<br>
            * Carnet Sanitario vigente.<a href="http://salud.jujuy.gob.ar/" target="blank">(Web del Ministerio de Salud)</a><br>
            * Planilla Prontuarial actualizada.<br>
        </div>
    </div>
  </div>
      
      
  <!--    <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title" data-toggle="collapse" data-parent="#accordion" href="#collapse4">
        RE-REGISTRO DE PROFSIONES COMPLEMENTARIAS DE LA SALUD
      </h4>
    </div>
    <div id="collapse4" class="panel-collapse collapse">
      <div class="panel-body">
          * Presentación de la "Planilla de Turno Otorgado".<br>
          * Fotocopia anverso y reverso del Documento Nacional de Identidad y acreditación identidad presentando el 
          original del mencionado documento. <br>
          Los extranjeros deberán poseer documento nacional de identidad emitido por Autoridad Argentina y cumplir con 
          las condiciones migratorias previstas en la Ley 25.871 y legislación concordante. Carta de ciudadanía para el 
          caso de argentinos naturalizados.<br>
          * Original del Certificado, que deberá cumplir con las condiciones de registración y legalización.<br>
          * Fotocopia doble faz en tamaño A4 del Certificado debidamente legalizado por la Institución formadora.<br>
          * Constancia de número de CUIT o CUIL.<br>
          * Certificado de Residencia, expedido por autoridad policial (Vigencia 1 año).<br>
          * Declaración Jurada de datos personales del número de teléfono de línea y/o celular y dirección de correo 
          electrónico si tuviere.<br>
          * Carnet Sanitario vigente.<br>
          * Planilla Prontuarial actualizada.<br>
          * Certificado de Reincidencia vigente.<br>
          * Presentar la credencial oportunamente otorgada para su agregación al legajo personal, o en su defecto la 
          respectiva denuncia de extravío.<br>
          * Certificado de ética o libre sanción profesional correspondiente al último registro que conste en el 
          título/diploma o certificado la misma tiene 30 días de validez de la fecha de emisión. Si la matricula fue 
          dada de baja constancia de la misma.<br>
          * Carpeta colgante.<br> 
      </div>
    </div>
  </div>
    -->
      
      <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title" data-toggle="collapse" data-parent="#accordion1" href="#collapse5">
        CONSTANCIA DE MATRÍCULA ACTIVA
      </h4>
    </div>
    <div id="collapse5" class="panel-collapse collapse">
      <div class="panel-body">
          Para obtener una Constancia de Matrícula Activa, el interesado deberá:<br>
          * Solicitar Constancia por Internet.<br>
          * Completar Formulario de Solicitud.<br>
          * Copia certificada de Carnet entregado al momento de la inscripción.<br>
          * Abonar, indefectiblemente, en la Tesorería de la Dirección General de Administración del Ministerio de Salud 
          el arancel correspondiente especificado en sección Aranceles.<br>
     </div>
    </div>
      </div>    
        
      <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title" data-toggle="collapse" data-parent="#accordion1" href="#collapse6">
        DUPLICADO DE MATRÍCULA
      </h4>
    </div>
    <div id="collapse6" class="panel-collapse collapse">
        <div class="panel-body">
            Para obtener un duplicado del carnet de matriculación, el interesado deberá presentar:<br>
            * Solicitar Turno por internet.<br>
            * Exposición policial donde conste la denuncia de extravío del carnet original, declarando la profesión y 
            el número de matrícula.<br>
            * Formulario de Declaración jurada de datos personales.<br>
            * Abonar, indefectiblemente, en la Tesorería de la Dirección General de Administración del Ministerio de Salud el 
              arancel correspondiente especificado en sección Aranceles.<br>
        </div>
    </div>
  </div>
        
        
      <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title" data-toggle="collapse" data-parent="#accordion1" href="#collapse7">
          BAJA DE MATRÍCULA
      </h4>
    </div>
    <div id="collapse7" class="panel-collapse collapse">
        <div class="panel-body">
            Para dar de baja la inscripción de una matrícula, el interesado deberá presentar: <br>
            * Solicitar Turno por internet.<br>
            * Presentar Constancia de no poseer Sumario Administrativo expedida por la Dirección Provincial de Personal.<br>
            * Presentar las certificaciones correspondientes a Libre Sanción Profesional del o de los Establecimientos en los que 
              haya trabajado en la provincia.<br>
            * Abonar, indefectiblemente, en la Tesorería de la Dirección General de Administración del Ministerio de Salud el 
              arancel correspondiente especificado en sección Aranceles.<br>
        </div>
    </div>
  </div>
    
          <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title" data-toggle="collapse" data-parent="#accordion1" href="#collapse8">
          CERTIFICACIÓN DE LIBRE SANCION PROFESIONAL
      </h4>
    </div>
    <div id="collapse8" class="panel-collapse collapse">
        <div class="panel-body">
            Para solicitar la certificación de libre sanción profesional, el interesado deberá presentar: <br>
            * Solicitar Turno por internet.<br>
            * Presentar Constancia de no poseer Sumario Administrativo expedida por la Dirección Provincial de Personal.<br>
            * Presentar las certificaciones correspondientes a Libre Sanción Profesional del o de los Establecimientos en los que 
              haya trabajado en la provincia.<br>
            * Abonar, indefectiblemente, en la Tesorería de la Dirección General de Administración del Ministerio de Salud el 
              arancel correspondiente especificado en sección Aranceles<br>
        </div>
    </div>
  </div>
    
    
</div>
</div>   

<hr id='sep'>

<div>
    <?php echo Html::img('turnos/Aranceles.gif','Aranceles','class="img-responsive img1"')?>
</div>
<div class='informacion'>
    <h4>
        <p>*Matriculación: $60.- (sesenta pesos)</p>
        <p>*Re-Matriculación: $ 60.- (sesenta pesos)</p>
        <p>*Duplicados: $80.- (ochenta pesos)</p>
        <p>*Certificados de Libre Sanción Profesional: $100.- (cien pesos)</p>
        <p>*Baja de Matrículas: $100.- (cien pesos)</p>
        <p>*Constancias: $40.- (cuarenta pesos)</p>
    </h4>
</div>
<hr id='sep'>
<div>
    <?php echo Html::img('turnos/descargar.gif','descarga','class="img-responsive img1"')?>
</div>    
<div class="informacion">
<h4>
    <p> Requisitos <a href="/archivos/Requisitos.pdf" title="Resolucion" target="blank">Descargar</a> </p> 
</h4>
</div>
<hr id='sep'>


<div class="row"> 
<div class="col-md-4" style="text-align: center">
    <h3> Turnos para registro y matriculación</h3>
  <a href='/turnos/matriculado/verificar'>
  <?php echo Form::submitImage('turnos/BtnTurno.jpg','class="btnefe"')?>
</a> 
</div>

<div class="col-md-4" style="text-align: center">
    <h3> Otros trámites</h3>
  <a href='/turnos/tramite/verificar2'>
  <?php echo Form::submitImage('turnos/BtnTramite.jpg','class="btnefe"')?>
</a> 
</div>
<div class="col-md-4" style="text-align: center">
    <h3> Consultar turno</h3>
  <a href='/turnos/matriculado/consultas'>
  <?php echo Form::submitImage('turnos/BtnConsultar.png','class="btnefe"')?>
</a> 
</div>
</div>
<br>
<br>
