<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//localhost/piwik/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 2]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>

<?php echo Form::open('matriculado/verificar','POST','id="formexiste" class="form-inline" role="form"') ?>

<br/>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-lg-4 divinp">
        <div class="form-group">
            <label class="control-label">DNI</label>
            <?php echo Form::text('ExisteDni','class="form-control" maxlength="8" onkeypress="return valideKey(event)" onblur="return largoDni2(this.id,errdni)" required ');?>
            <span id="errdni" class="help-block"></span>
        </div>
        <div class="form-group ">
           
            <?php echo Form::submitImage('turnos/BtnBuscar.png','class="btnefe btnReduc" onclick="return CtrlarDni(ExisteDni)"')?>
        </div>
        <div class="form-group">
            <a href='/turnos/matriculado/index'>
            <?php echo Html::img('turnos/BtnCancelar.gif', 'Cancelar', 'class="btnefe btnReduc"')?>
            </a> 
        </div>
    </div>
    <div class="col-md-4">
 
    </div>
</div>

<?php echo Form::close();?>
<?php echo View::content()?>

